[package]
name = "gww"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.16"
dialoguer = { version = "0.12", features = ["fuzzy-select"] }
